module.exports = function(svg){

;var defs_1 = svg.append('defs')
  ;var pattern_2 = defs_1.append('pattern')
  .attr('id','bluestripe')
  .attr('patternUnits','userSpaceOnUse')
  .attr('x','0')
  .attr('y','0')
  .attr('width','10')
  .attr('height','10')
  .attr('viewBox','0 0 20 20')
  ;var rect_3 = pattern_2.append('rect')
  .attr('width','110%')
  .attr('height','110%')
  .attr('fill','#ffffff')
  ;var path_4 = pattern_2.append('path')
  .attr('d','M1,1h20v20h-20v-20')
  .attr('fill-opacity','0')
  .attr('stroke-width','0.74')
  .attr('stroke-dasharray','0,1,1')
  .attr('stroke','black')
  .attr('stroke-opacity', 0.5)

  ;var filter_5 = defs_1.append('filter')
  .attr('id','fuzz')
  .attr('x','0')
  .attr('y','0')
  ;var feTurbulence_6 = filter_5.append('feTurbulence')
  .attr('type','turbulence')
  .attr('result','t')
  .attr('baseFrequency','.2 .3')
  .attr('numOctaves','5')
  .attr('stitchTiles','stitch')

  ;var feColorMatrix_7 = filter_5.append('feColorMatrix')
  .attr('type','saturate')
  .attr('in','t')
  .attr('values','0')

  ;var rect_8 = svg.append('rect')
  .attr('x',-100)
  .attr('y',0)
  .attr('width', 768+200)
  .attr('height', 768)
  .attr('fill','url(#bluestripe)')
}
